name: Configuration Management
description:
projects:
  - dotenv
  - dotenv-rails
  - figaro
  - settingslogic
  - rails_config
  - configatron
  - configuration
  - rails-settings
  - ledermann-rails-settings
  - configliere
  - simpleconfig
  - confstruct
  - configurable_engine
  - global
  - app
  - rconfig
  - store_configurable
  - configtoolkit
  - yettings
  - app_config
  - configus
  - optimism
  - application_configuration
  - gaston
  - micon
  - configulations
  - configurability
  - acts_as_configurable
  - constantinople
  - dynamic_configuration
  - amberbit-config
  - config_fun
  - configloader
  - config_newton
  - config-me
  - user_config
  - dotconfig
  - informante
